### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by kostat** [CollinAlpert/Expressions#1]
This library is mostly written by me under Apache 2.0 license, any fork is required to retain all the copyright and other attribution notices (see 4.c in the license). Since you copied the library, please add an explicit copyright notice.

**Comment by CollinAlpert** [comment]
So is it enough to just add the Apache 2.0 license? Or do I need to write anything else? If so, what do you want me to write and where?

**Comment by kostat** [comment]
See [Apache License](https://www.apache.org/licenses/LICENSE-2.0#apply) recommendation. Add the following line at the top of the license (or inside a NOTICE file):

> Copyright 2019 https://github.com/TrigerSoft
